import { Router, type IRouter } from "express";
import { db, trainsTable } from "@workspace/db";
import { eq, ilike, or } from "drizzle-orm";

const router: IRouter = Router();

// ─── Route Stops Map ─────────────────────────────────────────────────────────
const ROUTE_STOPS: Record<string, string[]> = {
  "MUM-DEL": ["Borivali","Surat","Vadodara","Ratlam","Kota","Sawai Madhopur","Mathura"],
  "DEL-MUM": ["Mathura","Sawai Madhopur","Kota","Ratlam","Vadodara","Surat","Borivali"],
  "MUM-KOL": ["Kalyan","Bhusaval","Nagpur","Raipur","Bilaspur","Rourkela","Kharagpur"],
  "KOL-MUM": ["Kharagpur","Rourkela","Bilaspur","Raipur","Nagpur","Bhusaval","Kalyan"],
  "MUM-CHN": ["Pune","Solapur","Wadi","Bangalore","Jolarpettai","Katpadi"],
  "CHN-MUM": ["Katpadi","Jolarpettai","Bangalore","Wadi","Solapur","Pune"],
  "MUM-BLR": ["Pune","Solapur","Gulbarga","Wadi","Yeshvantpur"],
  "BLR-MUM": ["Yeshvantpur","Wadi","Gulbarga","Solapur","Pune"],
  "MUM-HYD": ["Pune","Solapur","Wadi","Gulbarga","Secunderabad"],
  "HYD-MUM": ["Secunderabad","Gulbarga","Wadi","Solapur","Pune"],
  "MUM-AMD": ["Borivali","Vapi","Surat","Bharuch","Vadodara","Anand","Nadiad"],
  "AMD-MUM": ["Nadiad","Anand","Vadodara","Bharuch","Surat","Vapi","Borivali"],
  "MUM-GOA": ["Panvel","Roha","Mangaon","Khed","Chiplun","Ratnagiri","Kudal","Pernem"],
  "GOA-MUM": ["Pernem","Kudal","Ratnagiri","Chiplun","Khed","Mangaon","Roha","Panvel"],
  "MUM-PUNE": ["Kalyan","Khopoli","Karjat","Lonavala","Pune"],
  "PUNE-MUM": ["Pune","Lonavala","Karjat","Khopoli","Kalyan"],
  "MUM-BSB": ["Kalyan","Bhusaval","Itarsi","Allahabad","Varanasi"],
  "BSB-MUM": ["Varanasi","Allahabad","Itarsi","Bhusaval","Kalyan"],
  "MUM-LKO": ["Kalyan","Bhusaval","Itarsi","Bhopal","Jhansi","Kanpur","Lucknow"],
  "LKO-MUM": ["Lucknow","Kanpur","Jhansi","Bhopal","Itarsi","Bhusaval","Kalyan"],
  "MUM-GKP": ["Kalyan","Bhusaval","Itarsi","Bhopal","Jhansi","Kanpur","Lucknow","Gorakhpur"],
  "GKP-MUM": ["Gorakhpur","Lucknow","Kanpur","Jhansi","Bhopal","Itarsi","Bhusaval","Kalyan"],
  "MUM-PAT": ["Kalyan","Bhusaval","Itarsi","Allahabad","Gaya","Patna"],
  "PAT-MUM": ["Patna","Gaya","Allahabad","Itarsi","Bhusaval","Kalyan"],
  "MUM-ASR": ["Borivali","Surat","Vadodara","Ratlam","Kota","Delhi","Ambala","Ludhiana"],
  "ASR-MUM": ["Ludhiana","Ambala","Delhi","Kota","Ratlam","Vadodara","Surat","Borivali"],
  "MUM-DDN": ["Borivali","Surat","Vadodara","Kota","Mathura","Delhi","Meerut","Haridwar"],
  "DDN-MUM": ["Haridwar","Meerut","Delhi","Mathura","Kota","Vadodara","Surat","Borivali"],
  "MUM-JAT": ["Borivali","Surat","Vadodara","Kota","Delhi","Ambala","Ludhiana","Jalandhar","Pathankot"],
  "JAT-MUM": ["Pathankot","Jalandhar","Ludhiana","Ambala","Delhi","Kota","Vadodara","Surat","Borivali"],
  "MUM-BBS": ["Kalyan","Bhusaval","Nagpur","Raipur","Sambalpur","Bhubaneswar"],
  "BBS-MUM": ["Bhubaneswar","Sambalpur","Raipur","Nagpur","Bhusaval","Kalyan"],
  "MUM-EKM": ["Roha","Ratnagiri","Mangalore","Shoranur","Thrissur","Ernakulam"],
  "EKM-MUM": ["Ernakulam","Thrissur","Shoranur","Mangalore","Ratnagiri","Roha"],
  "MUM-TVC": ["Roha","Ratnagiri","Mangalore","Shoranur","Ernakulam","Kottayam","Thiruvananthapuram"],
  "TVC-MUM": ["Thiruvananthapuram","Kottayam","Ernakulam","Shoranur","Mangalore","Ratnagiri","Roha"],
  "MUM-NGP": ["Kalyan","Bhusaval","Badnera","Nagpur"],
  "NGP-MUM": ["Nagpur","Badnera","Bhusaval","Kalyan"],
  "MUM-ALD": ["Kalyan","Bhusaval","Itarsi","Bhopal","Bina","Jhansi","Allahabad"],
  "ALD-MUM": ["Allahabad","Jhansi","Bina","Bhopal","Itarsi","Bhusaval","Kalyan"],
  "MUM-JAB": ["Kalyan","Bhusaval","Itarsi","Pipariya","Jabalpur"],
  "JAB-MUM": ["Jabalpur","Pipariya","Itarsi","Bhusaval","Kalyan"],
  "MUM-INDB": ["Kalyan","Bhusaval","Khandwa","Mhow","Indore"],
  "INDB-MUM": ["Indore","Mhow","Khandwa","Bhusaval","Kalyan"],
  "MUM-BPL": ["Kalyan","Bhusaval","Itarsi","Bhopal"],
  "BPL-MUM": ["Bhopal","Itarsi","Bhusaval","Kalyan"],
  "MUM-CBE": ["Pune","Solapur","Wadi","Bangalore","Salem","Coimbatore"],
  "CBE-MUM": ["Coimbatore","Salem","Bangalore","Wadi","Solapur","Pune"],
  "MUM-MDU": ["Pune","Solapur","Wadi","Bangalore","Salem","Madurai"],
  "MDU-MUM": ["Madurai","Salem","Bangalore","Wadi","Solapur","Pune"],
  "MUM-GHY": ["Kalyan","Bhusaval","Itarsi","Allahabad","Gaya","Patna","Muzaffarpur","Guwahati"],
  "GHY-MUM": ["Guwahati","Muzaffarpur","Patna","Gaya","Allahabad","Itarsi","Bhusaval","Kalyan"],
  "MUM-JP": ["Borivali","Surat","Vadodara","Ratlam","Ajmer","Jaipur"],
  "JP-MUM": ["Jaipur","Ajmer","Ratlam","Vadodara","Surat","Borivali"],
  "MUM-UDZ": ["Borivali","Surat","Vadodara","Ratlam","Chittorgarh","Udaipur"],
  "UDZ-MUM": ["Udaipur","Chittorgarh","Ratlam","Vadodara","Surat","Borivali"],
  "KOL-DEL": ["Kharagpur","Bhubaneswar","Balasore","Bhadrak","Cuttack","Vishakhapatnam","Rajamundry","Vijayawada","Nellore","Chennai"],
  "DEL-KOL": ["Chennai","Nellore","Vijayawada","Rajamundry","Vishakhapatnam","Cuttack","Bhadrak","Balasore","Bhubaneswar","Kharagpur"],
  "KOL-CHN": ["Kharagpur","Balasore","Bhubaneswar","Cuttack","Vijayawada","Nellore"],
  "CHN-KOL": ["Nellore","Vijayawada","Cuttack","Bhubaneswar","Balasore","Kharagpur"],
  "KOL-BLR": ["Kharagpur","Bhubaneswar","Vijayawada","Nellore","Chennai","Bangalore"],
  "BLR-KOL": ["Bangalore","Chennai","Nellore","Vijayawada","Bhubaneswar","Kharagpur"],
  "KOL-HYD": ["Kharagpur","Bhubaneswar","Vijayawada","Warangal","Hyderabad"],
  "HYD-KOL": ["Hyderabad","Warangal","Vijayawada","Bhubaneswar","Kharagpur"],
  "KOL-BBS": ["Kharagpur","Balasore","Bhadrak","Cuttack","Bhubaneswar"],
  "BBS-KOL": ["Bhubaneswar","Cuttack","Bhadrak","Balasore","Kharagpur"],
  "KOL-PAT": ["Asansol","Dhanbad","Gaya","Patna"],
  "PAT-KOL": ["Patna","Gaya","Dhanbad","Asansol"],
  "KOL-ASR": ["Asansol","Patna","Gaya","Varanasi","Allahabad","Kanpur","Delhi","Ambala","Ludhiana"],
  "ASR-KOL": ["Ludhiana","Ambala","Delhi","Kanpur","Allahabad","Varanasi","Gaya","Patna","Asansol"],
  "KOL-DDN": ["Asansol","Patna","Varanasi","Allahabad","Kanpur","Delhi","Haridwar","Dehradun"],
  "DDN-KOL": ["Dehradun","Haridwar","Delhi","Kanpur","Allahabad","Varanasi","Patna","Asansol"],
  "KOL-JAT": ["Asansol","Patna","Allahabad","Kanpur","Delhi","Ambala","Ludhiana","Jalandhar","Pathankot"],
  "JAT-KOL": ["Pathankot","Jalandhar","Ludhiana","Ambala","Delhi","Kanpur","Allahabad","Patna","Asansol"],
  "KOL-AII": ["Asansol","Patna","Allahabad","Kanpur","Delhi","Jaipur","Ajmer"],
  "AII-KOL": ["Ajmer","Jaipur","Delhi","Kanpur","Allahabad","Patna","Asansol"],
  "KOL-JP": ["Asansol","Patna","Allahabad","Agra","Mathura","Delhi","Jaipur"],
  "JP-KOL": ["Jaipur","Delhi","Mathura","Agra","Allahabad","Patna","Asansol"],
  "KOL-GHY": ["Asansol","Malda","New Jalpaiguri","Rangiya","Guwahati"],
  "GHY-KOL": ["Guwahati","Rangiya","New Jalpaiguri","Malda","Asansol"],
  "KOL-NJP": ["Asansol","Malda","New Jalpaiguri"],
  "NJP-KOL": ["New Jalpaiguri","Malda","Asansol"],
  "KOL-LKO": ["Asansol","Dhanbad","Gaya","Varanasi","Lucknow"],
  "LKO-KOL": ["Lucknow","Varanasi","Gaya","Dhanbad","Asansol"],
  "KOL-BSB": ["Asansol","Dhanbad","Gaya","Varanasi"],
  "BSB-KOL": ["Varanasi","Gaya","Dhanbad","Asansol"],
  "KOL-RNC": ["Kharagpur","Tatanagar","Ranchi"],
  "RNC-KOL": ["Ranchi","Tatanagar","Kharagpur"],
  "DEL-CHN": ["Mathura","Agra","Jhansi","Bhopal","Nagpur","Vijayawada","Nellore"],
  "CHN-DEL": ["Nellore","Vijayawada","Nagpur","Bhopal","Jhansi","Agra","Mathura"],
  "DEL-BLR": ["Mathura","Agra","Jhansi","Bhopal","Nagpur","Hyderabad","Bangalore"],
  "BLR-DEL": ["Bangalore","Hyderabad","Nagpur","Bhopal","Jhansi","Agra","Mathura"],
  "DEL-HYD": ["Mathura","Agra","Jhansi","Nagpur","Hyderabad"],
  "HYD-DEL": ["Hyderabad","Nagpur","Jhansi","Agra","Mathura"],
  "DEL-JAB": ["Mathura","Agra","Jhansi","Bhopal","Itarsi","Jabalpur"],
  "JAB-DEL": ["Jabalpur","Itarsi","Bhopal","Jhansi","Agra","Mathura"],
  "DEL-BPL": ["Mathura","Agra","Gwalior","Jhansi","Bhopal"],
  "BPL-DEL": ["Bhopal","Jhansi","Gwalior","Agra","Mathura"],
  "DEL-BBS": ["Kanpur","Allahabad","Gaya","Patna","Dhanbad","Tatanagar","Bhubaneswar"],
  "BBS-DEL": ["Bhubaneswar","Tatanagar","Dhanbad","Patna","Gaya","Allahabad","Kanpur"],
  "DEL-LKO": ["Ghaziabad","Kanpur","Lucknow"],
  "LKO-DEL": ["Lucknow","Kanpur","Ghaziabad"],
  "DEL-ASR": ["Panipat","Ambala","Ludhiana","Jalandhar","Amritsar"],
  "ASR-DEL": ["Amritsar","Jalandhar","Ludhiana","Ambala","Panipat"],
  "DEL-CDG": ["Panipat","Ambala","Chandigarh"],
  "CDG-DEL": ["Chandigarh","Ambala","Panipat"],
  "DEL-DDN": ["Ghaziabad","Meerut","Saharanpur","Haridwar","Dehradun"],
  "DDN-DEL": ["Dehradun","Haridwar","Saharanpur","Meerut","Ghaziabad"],
  "DEL-JAT": ["Panipat","Ambala","Ludhiana","Jalandhar","Pathankot","Jammu"],
  "JAT-DEL": ["Jammu","Pathankot","Jalandhar","Ludhiana","Ambala","Panipat"],
  "DEL-JU": ["Rewari","Phulera","Merta Road","Jodhpur"],
  "JU-DEL": ["Jodhpur","Merta Road","Phulera","Rewari"],
  "DEL-AII": ["Mathura","Bharatpur","Sawai Madhopur","Jaipur","Ajmer"],
  "AII-DEL": ["Ajmer","Jaipur","Sawai Madhopur","Bharatpur","Mathura"],
  "DEL-JP": ["Mathura","Bharatpur","Bandikui","Jaipur"],
  "JP-DEL": ["Jaipur","Bandikui","Bharatpur","Mathura"],
  "DEL-BKN": ["Rewari","Suratgarh","Bikaner"],
  "BKN-DEL": ["Bikaner","Suratgarh","Rewari"],
  "DEL-UDZ": ["Mathura","Jaipur","Ajmer","Chittorgarh","Udaipur"],
  "UDZ-DEL": ["Udaipur","Chittorgarh","Ajmer","Jaipur","Mathura"],
  "DEL-BSB": ["Kanpur","Allahabad","Varanasi"],
  "BSB-DEL": ["Varanasi","Allahabad","Kanpur"],
  "DEL-PAT": ["Kanpur","Allahabad","Gaya","Patna"],
  "PAT-DEL": ["Patna","Gaya","Allahabad","Kanpur"],
  "DEL-GKP": ["Kanpur","Lucknow","Gorakhpur"],
  "GKP-DEL": ["Gorakhpur","Lucknow","Kanpur"],
  "DEL-KGM": ["Rampur","Moradabad","Rudrapur","Haldwani","Kathgodam"],
  "KGM-DEL": ["Kathgodam","Haldwani","Rudrapur","Moradabad","Rampur"],
  "DEL-GHY": ["Kanpur","Patna","Muzaffarpur","Katihar","Guwahati"],
  "GHY-DEL": ["Guwahati","Katihar","Muzaffarpur","Patna","Kanpur"],
  "CHN-BLR": ["Jolarpettai","Katpadi","Krishnarajapuram","Bangalore"],
  "BLR-CHN": ["Bangalore","Krishnarajapuram","Katpadi","Jolarpettai"],
  "CHN-HYD": ["Gudur","Nellore","Vijayawada","Warangal","Hyderabad"],
  "HYD-CHN": ["Hyderabad","Warangal","Vijayawada","Nellore","Gudur"],
  "CHN-MDU": ["Chengalpattu","Villupuram","Trichy","Madurai"],
  "MDU-CHN": ["Madurai","Trichy","Villupuram","Chengalpattu"],
  "CHN-CBE": ["Salem","Erode","Tiruppur","Coimbatore"],
  "CBE-CHN": ["Coimbatore","Tiruppur","Erode","Salem"],
  "CHN-EKM": ["Gudur","Nellore","Vijayawada","Bangalore","Shoranur","Ernakulam"],
  "EKM-CHN": ["Ernakulam","Shoranur","Bangalore","Vijayawada","Nellore","Gudur"],
  "CHN-TVC": ["Chengalpattu","Villupuram","Cuddalore","Nagapattinam","Nagercoil","Thiruvananthapuram"],
  "TVC-CHN": ["Thiruvananthapuram","Nagercoil","Nagapattinam","Cuddalore","Villupuram","Chengalpattu"],
  "CHN-GOA": ["Renigunta","Krishnarajapuram","Hassan","Mangalore","Madgaon"],
  "GOA-CHN": ["Madgaon","Mangalore","Hassan","Krishnarajapuram","Renigunta"],
  "BLR-HYD": ["Dharmavaram","Kurnool","Hyderabad"],
  "HYD-BLR": ["Hyderabad","Kurnool","Dharmavaram"],
  "BLR-TVC": ["Salem","Coimbatore","Palakkad","Shoranur","Ernakulam","Thiruvananthapuram"],
  "TVC-BLR": ["Thiruvananthapuram","Ernakulam","Shoranur","Palakkad","Coimbatore","Salem"],
  "BLR-EKM": ["Salem","Palakkad","Shoranur","Ernakulam"],
  "EKM-BLR": ["Ernakulam","Shoranur","Palakkad","Salem"],
  "BLR-BLR": ["Mysore","Arsikere","Hubli","Dharwad"],
  "BLR-GOA": ["Hubli","Londa","Castle Rock","Kulem","Madgaon"],
  "GOA-BLR": ["Madgaon","Kulem","Castle Rock","Londa","Hubli"],
  "BLR-GHY": ["Vijayawada","Bhubaneswar","Kharagpur","Asansol","Guwahati"],
  "GHY-BLR": ["Guwahati","Asansol","Kharagpur","Bhubaneswar","Vijayawada"],
  "BLR-AII": ["Salem","Coimbatore","Ernakulam","Shoranur","Mangalore","Mumbai","Vadodara","Ajmer"],
  "AII-BLR": ["Ajmer","Vadodara","Mumbai","Mangalore","Shoranur","Ernakulam","Coimbatore","Salem"],
  "BLR-PAT": ["Hyderabad","Nagpur","Raipur","Tatanagar","Gaya","Patna"],
  "PAT-BLR": ["Patna","Gaya","Tatanagar","Raipur","Nagpur","Hyderabad"],
  "HYD-HYD": ["Secunderabad","Nampally","Kacheguda","Warangal","Vijayawada"],
  "HYD-AII": ["Nagpur","Bhopal","Jhansi","Mathura","Jaipur","Ajmer"],
  "AII-HYD": ["Ajmer","Jaipur","Mathura","Jhansi","Bhopal","Nagpur"],
  "HYD-ASR": ["Nagpur","Bhopal","Jhansi","Delhi","Ambala","Amritsar"],
  "ASR-HYD": ["Amritsar","Ambala","Delhi","Jhansi","Bhopal","Nagpur"],
  "HYD-JAT": ["Nagpur","Bhopal","Jhansi","Delhi","Ambala","Jammu"],
  "JAT-HYD": ["Jammu","Ambala","Delhi","Jhansi","Bhopal","Nagpur"],
  "HYD-NGP": ["Kazipet","Balharshah","Nagpur"],
  "NGP-HYD": ["Nagpur","Balharshah","Kazipet"],
  "HYD-DEL": ["Kazipet","Nagpur","Bhopal","Jhansi","Agra","New Delhi"],
  "HYD-TVC": ["Guntakal","Bangalore","Coimbatore","Ernakulam","Thiruvananthapuram"],
  "TVC-HYD": ["Thiruvananthapuram","Ernakulam","Coimbatore","Bangalore","Guntakal"],
  "HYD-EKM": ["Guntakal","Bangalore","Shoranur","Ernakulam"],
  "EKM-HYD": ["Ernakulam","Shoranur","Bangalore","Guntakal"],
  "HYD-JU": ["Nagpur","Kota","Phulera","Jodhpur"],
  "JU-HYD": ["Jodhpur","Phulera","Kota","Nagpur"],
  "HYD-BKN": ["Secunderabad","Nagpur","Kota","Phulera","Bikaner"],
  "BKN-HYD": ["Bikaner","Phulera","Kota","Nagpur","Secunderabad"],
  "HYD-MDU": ["Guntakal","Salem","Trichy","Madurai"],
  "MDU-HYD": ["Madurai","Trichy","Salem","Guntakal"],
  "AMD-DEL": ["Mahesana","Palanpur","Ajmer","Jaipur","Mathura","New Delhi"],
  "DEL-AMD": ["New Delhi","Mathura","Jaipur","Ajmer","Palanpur","Mahesana"],
  "AMD-KOL": ["Vadodara","Surat","Mumbai","Nagpur","Raipur","Tatanagar","Howrah"],
  "KOL-AMD": ["Howrah","Tatanagar","Raipur","Nagpur","Mumbai","Surat","Vadodara"],
  "AMD-CHN": ["Vadodara","Mumbai","Pune","Solapur","Wadi","Chennai"],
  "CHN-AMD": ["Chennai","Wadi","Solapur","Pune","Mumbai","Vadodara"],
  "AMD-BLR": ["Vadodara","Mumbai","Pune","Wadi","Bangalore"],
  "BLR-AMD": ["Bangalore","Wadi","Pune","Mumbai","Vadodara"],
  "AMD-PUNE": ["Surat","Mumbai","Pune"],
  "PUNE-AMD": ["Pune","Mumbai","Surat"],
  "AMD-AII": ["Mahesana","Palanpur","Ajmer"],
  "AII-AMD": ["Ajmer","Palanpur","Mahesana"],
  "AMD-JU": ["Palanpur","Pali","Jodhpur"],
  "JU-AMD": ["Jodhpur","Pali","Palanpur"],
  "AMD-JP": ["Mahesana","Palanpur","Ajmer","Jaipur"],
  "JP-AMD": ["Jaipur","Ajmer","Palanpur","Mahesana"],
  "AMD-JAT": ["Palanpur","Ajmer","Jaipur","Delhi","Ambala","Jammu"],
  "JAT-AMD": ["Jammu","Ambala","Delhi","Jaipur","Ajmer","Palanpur"],
  "AMD-PAT": ["Vadodara","Mumbai","Nagpur","Raipur","Patna"],
  "PAT-AMD": ["Patna","Raipur","Nagpur","Mumbai","Vadodara"],
  "AMD-BSB": ["Vadodara","Kota","Agra","Allahabad","Varanasi"],
  "BSB-AMD": ["Varanasi","Allahabad","Agra","Kota","Vadodara"],
  "AMD-DDN": ["Palanpur","Ajmer","Jaipur","Delhi","Haridwar","Dehradun"],
  "DDN-AMD": ["Dehradun","Haridwar","Delhi","Jaipur","Ajmer","Palanpur"],
  "AMD-NGP": ["Surat","Bhusaval","Akola","Amravati","Nagpur"],
  "NGP-AMD": ["Nagpur","Amravati","Akola","Bhusaval","Surat"],
  "AMD-BBS": ["Mumbai","Nagpur","Raipur","Sambalpur","Bhubaneswar"],
  "BBS-AMD": ["Bhubaneswar","Sambalpur","Raipur","Nagpur","Mumbai"],
  "AMD-UDZ": ["Palanpur","Falna","Marwar","Chittorgarh","Udaipur"],
  "UDZ-AMD": ["Udaipur","Chittorgarh","Marwar","Falna","Palanpur"],
  "AMD-GKP": ["Vadodara","Kota","Agra","Kanpur","Gorakhpur"],
  "GKP-AMD": ["Gorakhpur","Kanpur","Agra","Kota","Vadodara"],
  "AMD-GHY": ["Mumbai","Nagpur","Nagpur","Guwahati"],
  "GHY-AMD": ["Guwahati","Nagpur","Mumbai"],
  "AMD-LKO": ["Vadodara","Kota","Agra","Kanpur","Lucknow"],
  "LKO-AMD": ["Lucknow","Kanpur","Agra","Kota","Vadodara"],
  "AMD-CDG": ["Ajmer","Jaipur","Delhi","Ambala","Chandigarh"],
  "CDG-AMD": ["Chandigarh","Ambala","Delhi","Jaipur","Ajmer"],
  "AMD-TVC": ["Mumbai","Mangalore","Shoranur","Ernakulam","Thiruvananthapuram"],
  "TVC-AMD": ["Thiruvananthapuram","Ernakulam","Shoranur","Mangalore","Mumbai"],
  "AMD-EKM": ["Mumbai","Mangalore","Shoranur","Ernakulam"],
  "EKM-AMD": ["Ernakulam","Shoranur","Mangalore","Mumbai"],
  "AMD-INDB": ["Vadodara","Ratlam","Indore"],
  "INDB-AMD": ["Indore","Ratlam","Vadodara"],
  "INDB-DEL": ["Ujjain","Maksi","Bhopal","Jhansi","Gwalior","Mathura","New Delhi"],
  "DEL-INDB": ["New Delhi","Mathura","Gwalior","Jhansi","Bhopal","Maksi","Ujjain"],
  "INDB-BPL": ["Ujjain","Dewas","Bhopal"],
  "BPL-INDB": ["Bhopal","Dewas","Ujjain"],
  "INDB-NGP": ["Mhow","Khandwa","Bhusaval","Nagpur"],
  "NGP-INDB": ["Nagpur","Bhusaval","Khandwa","Mhow"],
  "INDB-JP": ["Ratlam","Ajmer","Phulera","Jaipur"],
  "JP-INDB": ["Jaipur","Phulera","Ajmer","Ratlam"],
  "INDB-JAB": ["Ujjain","Bhopal","Itarsi","Pipariya","Jabalpur"],
  "JAB-INDB": ["Jabalpur","Pipariya","Itarsi","Bhopal","Ujjain"],
  "INDB-JU": ["Ratlam","Ajmer","Phulera","Merta Road","Jodhpur"],
  "JU-INDB": ["Jodhpur","Merta Road","Phulera","Ajmer","Ratlam"],
  "INDB-TVC": ["Khandwa","Bhusaval","Mumbai","Mangalore","Ernakulam","Thiruvananthapuram"],
  "TVC-INDB": ["Thiruvananthapuram","Ernakulam","Mangalore","Mumbai","Bhusaval","Khandwa"],
  "INDB-ASR": ["Ratlam","Kota","Agra","Delhi","Ambala","Amritsar"],
  "ASR-INDB": ["Amritsar","Ambala","Delhi","Agra","Kota","Ratlam"],
  "INDB-CDG": ["Bhopal","Jhansi","Agra","Delhi","Ambala","Chandigarh"],
  "CDG-INDB": ["Chandigarh","Ambala","Delhi","Agra","Jhansi","Bhopal"],
  "INDB-BLR": ["Khandwa","Nagpur","Hyderabad","Bangalore"],
  "BLR-INDB": ["Bangalore","Hyderabad","Nagpur","Khandwa"],
  "INDB-PAT": ["Bhopal","Itarsi","Allahabad","Gaya","Patna"],
  "PAT-INDB": ["Patna","Gaya","Allahabad","Itarsi","Bhopal"],
  "INDB-UDZ": ["Ratlam","Chittorgarh","Udaipur"],
  "UDZ-INDB": ["Udaipur","Chittorgarh","Ratlam"],
  "INDB-JAT": ["Bhopal","Jhansi","Agra","Delhi","Ambala","Jammu"],
  "JAT-INDB": ["Jammu","Ambala","Delhi","Agra","Jhansi","Bhopal"],
  "BPL-JAB": ["Itarsi","Pipariya","Narsinghpur","Jabalpur"],
  "JAB-BPL": ["Jabalpur","Narsinghpur","Pipariya","Itarsi"],
  "BPL-DEL": ["Jhansi","Gwalior","Agra","Mathura","New Delhi"],
  "BPL-BSP": ["Itarsi","Nagpur","Raipur","Bilaspur"],
  "BSP-BPL": ["Bilaspur","Raipur","Nagpur","Itarsi"],
  "BPL-LKO": ["Jhansi","Kanpur","Lucknow"],
  "LKO-BPL": ["Lucknow","Kanpur","Jhansi"],
  "BPL-AII": ["Jhansi","Gwalior","Mathura","Bharatpur","Jaipur","Ajmer"],
  "AII-BPL": ["Ajmer","Jaipur","Bharatpur","Mathura","Gwalior","Jhansi"],
  "JAB-JAT": ["Itarsi","Bhopal","Jhansi","Agra","Delhi","Ambala","Jammu"],
  "JAT-JAB": ["Jammu","Ambala","Delhi","Agra","Jhansi","Bhopal","Itarsi"],
  "JAB-KOL": ["Katni","Chopan","Garhwa Road","Subarnarekha","Tatanagar","Howrah"],
  "KOL-JAB": ["Howrah","Tatanagar","Subarnarekha","Chopan","Katni"],
  "JAB-RWA": ["Satna","Rewa"],
  "RWA-JAB": ["Rewa","Satna"],
  "JAB-AII": ["Bina","Guna","Ruthiyai","Kota","Ajmer"],
  "AII-JAB": ["Ajmer","Kota","Ruthiyai","Guna","Bina"],
  "JAB-BSP": ["Katni","Amarkantak","Bilaspur"],
  "BSP-JAB": ["Bilaspur","Amarkantak","Katni"],
  "NGP-JAB": ["Narsinghpur","Pipariya","Jabalpur"],
  "JAB-NGP": ["Jabalpur","Pipariya","Narsinghpur"],
  "NGP-DEL": ["Bhopal","Jhansi","Agra","New Delhi"],
  "DEL-NGP": ["New Delhi","Agra","Jhansi","Bhopal"],
  "NGP-BLR": ["Hyderabad","Guntakal","Bangalore"],
  "BLR-NGP": ["Bangalore","Guntakal","Hyderabad"],
  "NGP-BSP": ["Raipur","Bilaspur"],
  "BSP-NGP": ["Bilaspur","Raipur"],
  "NGP-KOL": ["Raipur","Tatanagar","Howrah"],
  "KOL-NGP": ["Howrah","Tatanagar","Raipur"],
  "NGP-AII": ["Bhopal","Jhansi","Mathura","Bharatpur","Jaipur","Ajmer"],
  "AII-NGP": ["Ajmer","Jaipur","Bharatpur","Mathura","Jhansi","Bhopal"],
  "NGP-NGP": ["Amravati","Badnera","Akola"],
  "NGP-HYD": ["Balharshah","Kazipet","Hyderabad"],
  "NGP-PUNE": ["Bhusaval","Pune"],
  "PUNE-NGP": ["Pune","Bhusaval"],
  "PUNE-HYD": ["Solapur","Wadi","Hyderabad"],
  "HYD-PUNE": ["Hyderabad","Wadi","Solapur"],
  "PUNE-KOL": ["Bhusaval","Nagpur","Raipur","Bilaspur","Tatanagar","Howrah"],
  "KOL-PUNE": ["Howrah","Tatanagar","Bilaspur","Raipur","Nagpur","Bhusaval"],
  "PUNE-BSB": ["Bhusaval","Nagpur","Allahabad","Varanasi"],
  "BSB-PUNE": ["Varanasi","Allahabad","Nagpur","Bhusaval"],
  "PUNE-LKO": ["Bhusaval","Nagpur","Allahabad","Kanpur","Lucknow"],
  "LKO-PUNE": ["Lucknow","Kanpur","Allahabad","Nagpur","Bhusaval"],
  "PUNE-EKM": ["Kolhapur","Londa","Mangalore","Shoranur","Ernakulam"],
  "EKM-PUNE": ["Ernakulam","Shoranur","Mangalore","Londa","Kolhapur"],
  "PUNE-JAT": ["Bhusaval","Nagpur","Bhopal","Agra","Delhi","Ambala","Jammu"],
  "JAT-PUNE": ["Jammu","Ambala","Delhi","Agra","Bhopal","Nagpur","Bhusaval"],
  "PUNE-GKP": ["Bhusaval","Nagpur","Itarsi","Bhopal","Jhansi","Kanpur","Gorakhpur"],
  "GKP-PUNE": ["Gorakhpur","Kanpur","Jhansi","Bhopal","Itarsi","Nagpur","Bhusaval"],
  "PUNE-PAT": ["Bhusaval","Nagpur","Raipur","Gaya","Patna"],
  "PAT-PUNE": ["Patna","Gaya","Raipur","Nagpur","Bhusaval"],
  "PUNE-DEL": ["Bhusaval","Nagpur","Bhopal","Jhansi","Agra","New Delhi"],
  "DEL-PUNE": ["New Delhi","Agra","Jhansi","Bhopal","Nagpur","Bhusaval"],
  "PUNE-JP": ["Bhusaval","Kota","Sawai Madhopur","Jaipur"],
  "JP-PUNE": ["Jaipur","Sawai Madhopur","Kota","Bhusaval"],
  "PUNE-BLR": ["Solapur","Wadi","Gulbarga","Yesvantpur"],
  "BLR-PUNE": ["Yesvantpur","Gulbarga","Wadi","Solapur"],
  "PUNE-BSP": ["Bhusaval","Nagpur","Raipur","Bilaspur"],
  "BSP-PUNE": ["Bilaspur","Raipur","Nagpur","Bhusaval"],
  "PUNE-INDB": ["Bhusaval","Khandwa","Indore"],
  "INDB-PUNE": ["Indore","Khandwa","Bhusaval"],
  "BSP-DEL": ["Raipur","Nagpur","Bhopal","Jhansi","Agra","New Delhi"],
  "DEL-BSP": ["New Delhi","Agra","Jhansi","Bhopal","Nagpur","Raipur"],
  "BSP-KOL": ["Raipur","Nagpur","Tatanagar","Howrah"],
  "KOL-BSP": ["Howrah","Tatanagar","Nagpur","Raipur"],
  "BSP-HYD": ["Raipur","Nagpur","Kazipet","Hyderabad"],
  "HYD-BSP": ["Hyderabad","Kazipet","Nagpur","Raipur"],
  "BSP-AII": ["Raipur","Nagpur","Bhopal","Jhansi","Mathura","Ajmer"],
  "AII-BSP": ["Ajmer","Mathura","Jhansi","Bhopal","Nagpur","Raipur"],
  "BSP-JAT": ["Nagpur","Bhopal","Jhansi","Agra","Delhi","Ambala","Jammu"],
  "JAT-BSP": ["Jammu","Ambala","Delhi","Agra","Jhansi","Bhopal","Nagpur"],
  "BSP-BLR": ["Raipur","Nagpur","Hyderabad","Bangalore"],
  "BLR-BSP": ["Bangalore","Hyderabad","Nagpur","Raipur"],
  "BSP-BBS": ["Raipur","Sambalpur","Bhubaneswar"],
  "BBS-BSP": ["Bhubaneswar","Sambalpur","Raipur"],
  "BSP-CDG": ["Nagpur","Bhopal","Jhansi","Delhi","Ambala","Chandigarh"],
  "CDG-BSP": ["Chandigarh","Ambala","Delhi","Jhansi","Bhopal","Nagpur"],
  "BSP-JP": ["Nagpur","Bhopal","Jhansi","Mathura","Jaipur"],
  "JP-BSP": ["Jaipur","Mathura","Jhansi","Bhopal","Nagpur"],
  "BSP-ASR": ["Nagpur","Bhopal","Jhansi","Delhi","Ambala","Amritsar"],
  "ASR-BSP": ["Amritsar","Ambala","Delhi","Jhansi","Bhopal","Nagpur"],
  "RNC-DEL": ["Tatanagar","Dhanbad","Gaya","Allahabad","Kanpur","New Delhi"],
  "DEL-RNC": ["New Delhi","Kanpur","Allahabad","Gaya","Dhanbad","Tatanagar"],
  "RNC-BLR": ["Tatanagar","Kharagpur","Bhubaneswar","Vijayawada","Bangalore"],
  "BLR-RNC": ["Bangalore","Vijayawada","Bhubaneswar","Kharagpur","Tatanagar"],
  "RNC-MUM": ["Tatanagar","Nagpur","Bhusaval","Mumbai"],
  "MUM-RNC": ["Mumbai","Bhusaval","Nagpur","Tatanagar"],
  "RNC-AII": ["Tatanagar","Nagpur","Bhopal","Jhansi","Mathura","Ajmer"],
  "AII-RNC": ["Ajmer","Mathura","Jhansi","Bhopal","Nagpur","Tatanagar"],
  "RNC-PAT": ["Hatia","Barkakana","Koderma","Gaya","Patna"],
  "PAT-RNC": ["Patna","Gaya","Koderma","Barkakana","Hatia"],
  "RNC-EKM": ["Tatanagar","Nagpur","Hyderabad","Ernakulam"],
  "EKM-RNC": ["Ernakulam","Hyderabad","Nagpur","Tatanagar"],
  "RNC-BSB": ["Hatia","Barkakana","Gaya","Varanasi"],
  "BSB-RNC": ["Varanasi","Gaya","Barkakana","Hatia"],
  "RNC-BSP": ["Rourkela","Jharsuguda","Bilaspur"],
  "BSP-RNC": ["Bilaspur","Jharsuguda","Rourkela"],
  "RNC-KOL": ["Tatanagar","Kharagpur","Kolkata"],
  "KOL-RNC": ["Kolkata","Kharagpur","Tatanagar"],
  "RNC-HYD": ["Nagpur","Kazipet","Hyderabad"],
  "HYD-RNC": ["Hyderabad","Kazipet","Nagpur"],
  "RNC-JAT": ["Tatanagar","Nagpur","Bhopal","Delhi","Ambala","Jammu"],
  "JAT-RNC": ["Jammu","Ambala","Delhi","Bhopal","Nagpur","Tatanagar"],
  "BBS-BLR": ["Vijayawada","Nellore","Chennai","Katpadi","Bangalore"],
  "BLR-BBS": ["Bangalore","Katpadi","Chennai","Nellore","Vijayawada"],
  "BBS-DEL": ["Tatanagar","Dhanbad","Gaya","Allahabad","Kanpur","New Delhi"],
  "DEL-BBS": ["New Delhi","Kanpur","Allahabad","Gaya","Dhanbad","Tatanagar"],
  "BBS-HYD": ["Vijayawada","Warangal","Hyderabad"],
  "HYD-BBS": ["Hyderabad","Warangal","Vijayawada"],
  "BBS-CHN": ["Cuttack","Bhubaneswar","Vijayawada","Chennai"],
  "CHN-BBS": ["Chennai","Vijayawada","Bhubaneswar","Cuttack"],
  "BBS-PAT": ["Cuttack","Kharagpur","Asansol","Dhanbad","Gaya","Patna"],
  "PAT-BBS": ["Patna","Gaya","Dhanbad","Asansol","Kharagpur","Cuttack"],
  "BBS-AMD": ["Rourkela","Nagpur","Bhusaval","Mumbai","Surat","Vadodara","Ahmedabad"],
  "AMD-BBS": ["Ahmedabad","Vadodara","Surat","Mumbai","Bhusaval","Nagpur","Rourkela"],
  "BBS-AII": ["Rourkela","Nagpur","Bhopal","Jhansi","Mathura","Ajmer"],
  "AII-BBS": ["Ajmer","Mathura","Jhansi","Bhopal","Nagpur","Rourkela"],
  "BBS-JU": ["Rourkela","Nagpur","Bhopal","Jhansi","Mathura","Kota","Jodhpur"],
  "JU-BBS": ["Jodhpur","Kota","Mathura","Jhansi","Bhopal","Nagpur","Rourkela"],
  "BBS-DDN": ["Kharagpur","Asansol","Gaya","Varanasi","Allahabad","Delhi","Haridwar"],
  "DDN-BBS": ["Haridwar","Delhi","Allahabad","Varanasi","Gaya","Asansol","Kharagpur"],
  "PAT-LKO": ["Gaya","Allahabad","Varanasi","Jaunpur","Lucknow"],
  "LKO-PAT": ["Lucknow","Jaunpur","Varanasi","Allahabad","Gaya"],
  "PAT-GKP": ["Muzaffarpur","Gorakhpur"],
  "GKP-PAT": ["Gorakhpur","Muzaffarpur"],
  "PAT-BSB": ["Gaya","Allahabad","Varanasi"],
  "BSB-PAT": ["Varanasi","Allahabad","Gaya"],
  "PAT-ASR": ["Gaya","Allahabad","Kanpur","Delhi","Ambala","Amritsar"],
  "ASR-PAT": ["Amritsar","Ambala","Delhi","Kanpur","Allahabad","Gaya"],
  "PAT-JAT": ["Gaya","Allahabad","Kanpur","Delhi","Ambala","Jammu"],
  "JAT-PAT": ["Jammu","Ambala","Delhi","Kanpur","Allahabad","Gaya"],
  "PAT-NGP": ["Gaya","Allahabad","Nagpur"],
  "NGP-PAT": ["Nagpur","Allahabad","Gaya"],
  "PAT-AII": ["Allahabad","Kanpur","Delhi","Jaipur","Ajmer"],
  "AII-PAT": ["Ajmer","Jaipur","Delhi","Kanpur","Allahabad"],
  "PAT-CDG": ["Allahabad","Kanpur","Delhi","Ambala","Chandigarh"],
  "CDG-PAT": ["Chandigarh","Ambala","Delhi","Kanpur","Allahabad"],
  "LKO-ASR": ["Kanpur","Delhi","Ambala","Ludhiana","Amritsar"],
  "ASR-LKO": ["Amritsar","Ludhiana","Ambala","Delhi","Kanpur"],
  "LKO-JAT": ["Kanpur","Delhi","Ambala","Ludhiana","Jammu"],
  "JAT-LKO": ["Jammu","Ludhiana","Ambala","Delhi","Kanpur"],
  "LKO-CDG": ["Kanpur","Delhi","Ambala","Chandigarh"],
  "CDG-LKO": ["Chandigarh","Ambala","Delhi","Kanpur"],
  "LKO-BSB": ["Varanasi"],
  "BSB-LKO": ["Varanasi"],
  "LKO-ALD": ["Kanpur","Allahabad"],
  "ALD-LKO": ["Allahabad","Kanpur"],
  "LKO-GKP": ["Gorakhpur"],
  "GKP-LKO": ["Gorakhpur"],
  "LKO-HYD": ["Kanpur","Allahabad","Nagpur","Hyderabad"],
  "HYD-LKO": ["Hyderabad","Nagpur","Allahabad","Kanpur"],
  "LKO-BPL": ["Kanpur","Jhansi","Bhopal"],
  "BPL-LKO": ["Bhopal","Jhansi","Kanpur"],
  "LKO-KGM": ["Bareilly","Haldwani","Kathgodam"],
  "KGM-LKO": ["Kathgodam","Haldwani","Bareilly"],
  "ALD-DEL": ["Kanpur","Agra","New Delhi"],
  "DEL-ALD": ["New Delhi","Agra","Kanpur"],
  "BSB-DEL": ["Allahabad","Kanpur","Agra","New Delhi"],
  "DEL-BSB": ["New Delhi","Agra","Kanpur","Allahabad"],
  "BSB-JAT": ["Kanpur","Delhi","Ambala","Ludhiana","Jammu"],
  "JAT-BSB": ["Jammu","Ludhiana","Ambala","Delhi","Kanpur"],
  "BSB-GKP": ["Jaunpur","Gorakhpur"],
  "GKP-BSB": ["Gorakhpur","Jaunpur"],
  "BSB-AII": ["Allahabad","Kanpur","Delhi","Jaipur","Ajmer"],
  "AII-BSB": ["Ajmer","Jaipur","Delhi","Kanpur","Allahabad"],
  "BSB-KGM": ["Allahabad","Kanpur","Bareilly","Haldwani"],
  "KGM-BSB": ["Haldwani","Bareilly","Kanpur","Allahabad"],
  "BSB-MDU": ["Allahabad","Nagpur","Chennai","Madurai"],
  "MDU-BSB": ["Madurai","Chennai","Nagpur","Allahabad"],
  "BSB-DDN": ["Allahabad","Kanpur","Delhi","Haridwar","Dehradun"],
  "DDN-BSB": ["Dehradun","Haridwar","Delhi","Kanpur","Allahabad"],
  "GKP-HYD": ["Lucknow","Allahabad","Nagpur","Hyderabad"],
  "HYD-GKP": ["Hyderabad","Nagpur","Allahabad","Lucknow"],
  "GKP-BLR": ["Lucknow","Allahabad","Nagpur","Hyderabad","Bangalore"],
  "BLR-GKP": ["Bangalore","Hyderabad","Nagpur","Allahabad","Lucknow"],
  "GKP-TVC": ["Lucknow","Nagpur","Chennai","Thiruvananthapuram"],
  "TVC-GKP": ["Thiruvananthapuram","Chennai","Nagpur","Lucknow"],
  "GKP-JAT": ["Lucknow","Delhi","Ambala","Jammu"],
  "JAT-GKP": ["Jammu","Ambala","Delhi","Lucknow"],
  "GHY-DEL": ["Lumding","Guwahati","Katihar","Patna","Allahabad","Kanpur","New Delhi"],
  "DEL-GHY": ["New Delhi","Kanpur","Allahabad","Patna","Katihar","Guwahati","Lumding"],
  "GHY-NJP": ["Rangiya","Dhubri","New Jalpaiguri"],
  "NJP-GHY": ["New Jalpaiguri","Dhubri","Rangiya"],
  "NJP-DEL": ["Malda","Asansol","Allahabad","Kanpur","New Delhi"],
  "DEL-NJP": ["New Delhi","Kanpur","Allahabad","Asansol","Malda"],
  "NJP-PAT": ["Malda","Asansol","Gaya","Patna"],
  "PAT-NJP": ["Patna","Gaya","Asansol","Malda"],
  "NJP-ASR": ["Malda","Asansol","Allahabad","Delhi","Amritsar"],
  "ASR-NJP": ["Amritsar","Delhi","Allahabad","Asansol","Malda"],
  "MDU-DEL": ["Trichy","Jolarpettai","Bangalore","Nagpur","Bhopal","Agra","New Delhi"],
  "DEL-MDU": ["New Delhi","Agra","Bhopal","Nagpur","Bangalore","Jolarpettai","Trichy"],
  "MDU-JAT": ["Trichy","Chennai","Wadi","Nagpur","Delhi","Ambala","Jammu"],
  "JAT-MDU": ["Jammu","Ambala","Delhi","Nagpur","Wadi","Chennai","Trichy"],
  "MDU-AII": ["Trichy","Chennai","Nagpur","Bhopal","Ajmer"],
  "AII-MDU": ["Ajmer","Bhopal","Nagpur","Chennai","Trichy"],
  "MDU-DDN": ["Trichy","Chennai","Nagpur","Delhi","Haridwar","Dehradun"],
  "DDN-MDU": ["Dehradun","Haridwar","Delhi","Nagpur","Chennai","Trichy"],
  "CBE-DEL": ["Salem","Bangalore","Hyderabad","Nagpur","Bhopal","New Delhi"],
  "DEL-CBE": ["New Delhi","Bhopal","Nagpur","Hyderabad","Bangalore","Salem"],
  "EKM-DEL": ["Shoranur","Mangalore","Mumbai","Nagpur","New Delhi"],
  "DEL-EKM": ["New Delhi","Nagpur","Mumbai","Mangalore","Shoranur"],
  "EKM-TVC": ["Kottayam","Thiruvananthapuram"],
  "TVC-EKM": ["Thiruvananthapuram","Kottayam"],
  "EKM-PAT": ["Shoranur","Chennai","Hyderabad","Nagpur","Patna"],
  "PAT-EKM": ["Patna","Nagpur","Hyderabad","Chennai","Shoranur"],
  "TVC-DEL": ["Ernakulam","Mangalore","Mumbai","Nagpur","Bhopal","New Delhi"],
  "DEL-TVC": ["New Delhi","Bhopal","Nagpur","Mumbai","Mangalore","Ernakulam"],
  "TVC-GHY": ["Ernakulam","Mangalore","Mumbai","Nagpur","Guwahati"],
  "GHY-TVC": ["Guwahati","Nagpur","Mumbai","Mangalore","Ernakulam"],
  "TVC-CDG": ["Ernakulam","Mangalore","Mumbai","Vadodara","Ahmedabad","Delhi","Chandigarh"],
  "CDG-TVC": ["Chandigarh","Delhi","Ahmedabad","Vadodara","Mumbai","Mangalore","Ernakulam"],
  "TVC-ASR": ["Ernakulam","Mangalore","Mumbai","Vadodara","Ahmedabad","Delhi","Amritsar"],
  "ASR-TVC": ["Amritsar","Delhi","Ahmedabad","Vadodara","Mumbai","Mangalore","Ernakulam"],
  "GOA-DEL": ["Madgaon","Londa","Hubli","Wadi","Nagpur","Bhopal","New Delhi"],
  "DEL-GOA": ["New Delhi","Bhopal","Nagpur","Wadi","Hubli","Londa","Madgaon"],
  "GOA-PAT": ["Madgaon","Nagpur","Raipur","Tatanagar","Gaya","Patna"],
  "PAT-GOA": ["Patna","Gaya","Tatanagar","Raipur","Nagpur","Madgaon"],
  "GOA-CDG": ["Madgaon","Londa","Hubli","Wadi","Nagpur","Bhopal","Delhi","Chandigarh"],
  "CDG-GOA": ["Chandigarh","Delhi","Bhopal","Nagpur","Wadi","Hubli","Londa","Madgaon"],
  "JU-MUM": ["Merta Road","Phulera","Ajmer","Kota","Vadodara","Surat","Mumbai"],
  "MUM-JU": ["Mumbai","Surat","Vadodara","Kota","Ajmer","Phulera","Merta Road"],
  "JU-DEL": ["Merta Road","Phulera","Rewari","New Delhi"],
  "DEL-JU": ["New Delhi","Rewari","Phulera","Merta Road"],
  "JU-KOL": ["Marwar","Kota","Agra","Mathura","Kanpur","Allahabad","Gaya","Howrah"],
  "KOL-JU": ["Howrah","Gaya","Allahabad","Kanpur","Mathura","Agra","Kota","Marwar"],
  "JU-BLR": ["Marwar","Kota","Nagpur","Hyderabad","Bangalore"],
  "BLR-JU": ["Bangalore","Hyderabad","Nagpur","Kota","Marwar"],
  "JU-BBS": ["Marwar","Kota","Nagpur","Raipur","Bhubaneswar"],
  "BBS-JU": ["Bhubaneswar","Raipur","Nagpur","Kota","Marwar"],
  "BKN-MUM": ["Jodhpur","Merta Road","Phulera","Ajmer","Kota","Vadodara","Mumbai"],
  "MUM-BKN": ["Mumbai","Vadodara","Kota","Ajmer","Phulera","Jodhpur"],
  "BKN-KOL": ["Jodhpur","Kota","Agra","Allahabad","Gaya","Howrah"],
  "KOL-BKN": ["Howrah","Gaya","Allahabad","Agra","Kota","Jodhpur"],
  "JP-AII": ["Ajmer"],
  "AII-JP": ["Ajmer"],
  "JP-JAT": ["Jaipur","Delhi","Ambala","Ludhiana","Jammu"],
  "JAT-JP": ["Jammu","Ludhiana","Ambala","Delhi","Jaipur"],
  "CDG-ASR": ["Ambala","Ludhiana","Amritsar"],
  "ASR-CDG": ["Amritsar","Ludhiana","Ambala"],
  "CDG-JAT": ["Ambala","Ludhiana","Jalandhar","Pathankot","Jammu"],
  "JAT-CDG": ["Jammu","Pathankot","Jalandhar","Ludhiana","Ambala"],
  "KGM-JAT": ["Moradabad","Saharanpur","Ambala","Ludhiana","Jalandhar","Jammu"],
  "JAT-KGM": ["Jammu","Jalandhar","Ludhiana","Ambala","Saharanpur","Moradabad"],
  "KGM-ASR": ["Moradabad","Saharanpur","Ambala","Ludhiana","Amritsar"],
  "ASR-KGM": ["Amritsar","Ludhiana","Ambala","Saharanpur","Moradabad"],
  "DDN-ASR": ["Haridwar","Saharanpur","Ambala","Ludhiana","Amritsar"],
  "ASR-DDN": ["Amritsar","Ludhiana","Ambala","Saharanpur","Haridwar"],
  "DDN-JAT": ["Haridwar","Saharanpur","Ambala","Ludhiana","Pathankot","Jammu"],
  "JAT-DDN": ["Jammu","Pathankot","Ludhiana","Ambala","Saharanpur","Haridwar"],
  "ASR-JAT": ["Ludhiana","Jalandhar","Pathankot","Jammu"],
  "JAT-ASR": ["Jammu","Pathankot","Jalandhar","Ludhiana"],
};

function getRouteStops(routeKey: string): string[] {
  return ROUTE_STOPS[routeKey] ?? ["Intermediate Station"];
}

// ─── Live status computation ──────────────────────────────────────────────────
function computeLiveStatus(trainNumber: string, fromStation: string, toStation: string, routeKey: string) {
  const now = new Date();
  const seed = trainNumber.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  const totalMinsInDay = now.getHours() * 60 + now.getMinutes();
  const offset = seed % 240; // 0-240 minute offset per train
  const trainMins = (totalMinsInDay + offset) % 1440;

  // Map train position to percentage 0-100
  const percent = Math.round((trainMins / 1440) * 100);

  const stops = getRouteStops(routeKey);
  const allStops = [fromStation, ...stops, toStation];
  const stopIndex = Math.floor((percent / 100) * (allStops.length - 1));
  const currentIdx = Math.min(stopIndex, allStops.length - 1);

  const currentStation = allStops[currentIdx];
  const nextStation = currentIdx < allStops.length - 1 ? allStops[currentIdx + 1] : toStation;

  // Delay based on train seed
  const delaySeed = seed % 5;
  const delayMins = delaySeed === 0 ? 0 : delaySeed === 1 ? 5 : delaySeed === 2 ? 10 : delaySeed === 3 ? 0 : 15;

  // Stop statuses
  const stopsData = allStops.map((name, i) => {
    let status: "departed" | "current" | "upcoming";
    if (i < currentIdx) status = "departed";
    else if (i === currentIdx) status = "current";
    else status = "upcoming";

    const baseHour = 6 + Math.floor((i / allStops.length) * 18);
    const baseMins = (i * 47) % 60;
    const schedTime = `${String(baseHour).padStart(2, "0")}:${String(baseMins).padStart(2, "0")}`;

    return {
      code: name.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 5) || "STA",
      name,
      scheduledArrival: i === 0 ? null : schedTime,
      scheduledDeparture: i === allStops.length - 1 ? null : schedTime,
      actualArrival: (status === "departed" || status === "current") && i > 0
        ? `${String(baseHour).padStart(2, "0")}:${String(Math.min(59, baseMins + delayMins)).padStart(2, "0")}`
        : null,
      actualDeparture: status === "departed" && i < allStops.length - 1
        ? `${String(baseHour).padStart(2, "0")}:${String(Math.min(59, baseMins + delayMins)).padStart(2, "0")}`
        : null,
      platform: `${(seed + i) % 8 + 1}`,
      haltMins: i === 0 || i === allStops.length - 1 ? 0 : (i * 3) % 10 + 1,
      distance: Math.round((i / allStops.length) * 1500),
      day: i < allStops.length / 2 ? 1 : 2,
      delayMins: status === "departed" ? delayMins : status === "current" ? delayMins : 0,
      status,
    };
  });

  const trainType = trainNumber.startsWith("120") ? "Shatabdi"
    : trainNumber.startsWith("12") && parseInt(trainNumber) < 12300 ? "Jan Shatabdi"
    : parseInt(trainNumber) >= 12301 && parseInt(trainNumber) <= 12453 ? "Rajdhani"
    : parseInt(trainNumber) >= 12213 && parseInt(trainNumber) <= 12299 ? "Duronto"
    : "Express";

  return {
    trainNumber,
    trainName: null, // filled by caller
    trainType,
    from: fromStation,
    to: toStation,
    fromCode: fromStation.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 5),
    toCode: toStation.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 5),
    currentStation,
    nextStation,
    currentBetween: currentIdx < allStops.length - 1 ? [currentStation, nextStation] : null,
    percentComplete: percent,
    delayMins,
    lastUpdated: `${now.getHours()}:${String(now.getMinutes()).padStart(2, "0")}`,
    stops: stopsData,
  };
}

// ─── Routes ──────────────────────────────────────────────────────────────────

// GET /trains/live-status/:trainNumber
router.get("/trains/live-status/:trainNumber", async (req, res): Promise<void> => {
  const { trainNumber } = req.params;
  try {
    const [train] = await db
      .select()
      .from(trainsTable)
      .where(eq(trainsTable.trainNumber, trainNumber.trim()))
      .limit(1);

    if (!train) {
      res.status(404).json({ error: "Train not found", message: `Train ${trainNumber} is not in our database.` });
      return;
    }

    const liveData = computeLiveStatus(train.trainNumber, train.fromStation, train.toStation, train.routeKey);
    liveData.trainName = train.trainName;
    liveData.trainType = train.trainType;

    res.json({ success: true, data: liveData });
  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

// GET /trains/search?q=...
router.get("/trains/search", async (req, res): Promise<void> => {
  const q = (req.query.q as string ?? "").trim();
  if (!q || q.length < 2) {
    res.json({ success: true, data: [] });
    return;
  }
  try {
    const results = await db
      .select()
      .from(trainsTable)
      .where(
        or(
          ilike(trainsTable.trainNumber, `%${q}%`),
          ilike(trainsTable.trainName, `%${q}%`),
          ilike(trainsTable.fromStation, `%${q}%`),
          ilike(trainsTable.toStation, `%${q}%`),
        ),
      )
      .limit(20);
    res.json({ success: true, data: results });
  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

export default router;
