import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { packagesTable } from "./schema/packages.js";

const pool = new Pool({ connectionString: process.env["DATABASE_URL"] });
const db = drizzle(pool);

const packages = [
  {
    slug: "bali-paradise-escape",
    title: "Bali Paradise Escape",
    destination: "Bali",
    country: "Indonesia",
    theme: "Beach",
    durationNights: 6,
    durationDays: 7,
    price: "119999",
    offerPrice: "89999",
    currency: "INR",
    rating: 4.8,
    reviewCount: 342,
    overview: "Immerse yourself in the magical island of Bali with its emerald rice terraces, ancient temples, and pristine beaches. This curated journey blends spiritual discovery with luxurious relaxation in one of the world's most enchanting destinations.",
    highlights: ["Sunrise trek to Mount Batur volcano","Private villa with infinity pool","Traditional Balinese cooking class","Sacred Monkey Forest and Tirta Empul temple visit","Sunset dinner at Tanah Lot cliff temple","Ubud Art Market and royal palace tour"],
    inclusions: ["Return airfare from major Indian cities","6 nights luxury villa accommodation","Daily breakfast + 3 dinners","All transfers and airport pickup","English-speaking local guide","Bali cultural show tickets"],
    exclusions: ["Travel insurance","Personal expenses & shopping","Optional adventure activities","Visa fees (on-arrival free for 30 days)"],
    itinerary: [
      { day: 1, title: "Arrival & Seminyak", description: "Touch down in paradise. Transfer to your private villa in Seminyak.", activities: ["Airport pickup","Villa check-in","Welcome cocktails on the beach","Sunset at Ku De Ta"] },
      { day: 2, title: "Ubud Cultural Immersion", description: "Explore the cultural heart of Bali.", activities: ["Tegalalang Rice Terrace","Tirta Empul Temple","Ubud Art Market","Royal Palace evening tour"] },
      { day: 3, title: "Volcano & Hot Springs", description: "An early morning trek to witness sunrise above the clouds.", activities: ["4am Batur Trek","Crater rim breakfast","Natural hot spring bath","Afternoon at leisure"] },
      { day: 4, title: "Nusa Penida Island", description: "Day trip to the rugged cliffs and turquoise waters of Nusa Penida.", activities: ["Speedboat transfer","Kelingking Beach","Angel Billabong","Crystal Bay snorkeling"] },
      { day: 5, title: "Cooking & Wellness", description: "Connect with Balinese traditions through food, yoga and healing.", activities: ["Morning yoga session","Traditional cooking class","Sacred Monkey Forest","Spa & wellness treatment"] },
      { day: 6, title: "Tanah Lot & Seminyak", description: "Visit the iconic sea temple and enjoy your last full day in Bali.", activities: ["Tanah Lot temple sunset","Beach club afternoon","Farewell dinner at Jimbaran seafood"] },
      { day: 7, title: "Departure", description: "Check out and transfer to the airport.", activities: ["Breakfast","Last-minute shopping","Airport transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1604999565976-8913ad2ddb37?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 12, category: "Beach", isFeatured: true, isTrending: false, isPublished: true,
  },
  {
    slug: "maldives-overwater-luxury",
    title: "Maldives Overwater Luxury",
    destination: "Maldives",
    country: "Maldives",
    theme: "Romantic",
    durationNights: 4,
    durationDays: 5,
    price: "189999",
    offerPrice: "149999",
    currency: "INR",
    rating: 4.9,
    reviewCount: 218,
    overview: "Step into an otherworldly realm of crystal-clear lagoons and powdery white sands. Your overwater bungalow perches above a living coral reef, offering unparalleled privacy and romance.",
    highlights: ["Overwater bungalow with glass floor panels","Private plunge pool with ocean views","Sunset dolphin-watching cruise","PADI-certified diving at pristine reefs","Floating breakfast served in your pool","Couples spa with marine ingredients"],
    inclusions: ["Return seaplane or speedboat transfers","4 nights overwater villa","Full board (all meals included)","Non-motorised water sports","Snorkeling equipment","One sunset cruise"],
    exclusions: ["International flights","Scuba diving sessions","Spa treatments","Alcoholic beverages","Travel insurance"],
    itinerary: [
      { day: 1, title: "Arrival in Paradise", description: "Arrive at Malé and transfer to your resort via seaplane.", activities: ["Seaplane transfer","Villa check-in","Welcome snorkeling","Sunset cocktails"] },
      { day: 2, title: "Ocean & Reef", description: "Spend the day exploring the vibrant marine life.", activities: ["Floating breakfast in pool","House reef snorkeling","Dolphin sunset cruise","Candlelit dinner on the beach"] },
      { day: 3, title: "Adventure & Discovery", description: "Dive deeper into the Maldivian ocean.", activities: ["Morning diving session","Sandbank picnic lunch","Manta ray snorkel trip","Star-gazing dinner"] },
      { day: 4, title: "Pure Relaxation", description: "The ultimate day of indulgence and spa treatments.", activities: ["Floating breakfast","Couples ocean spa","Water sports afternoon","Chef's table dinner"] },
      { day: 5, title: "Farewell", description: "Last morning in paradise.", activities: ["Sunrise swim","Checkout breakfast","Seaplane transfer to Malé"] },
    ],
    images: ["https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1573843981267-be1999ff37cd?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1540202404-a2f29016b523?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 2, category: "Romantic", isFeatured: false, isTrending: true, isPublished: true,
  },
  {
    slug: "paris-romance-trail",
    title: "Paris Romance Trail",
    destination: "Paris",
    country: "France",
    theme: "Romantic",
    durationNights: 5,
    durationDays: 6,
    price: "159999",
    offerPrice: "129999",
    currency: "INR",
    rating: 4.7,
    reviewCount: 284,
    overview: "The city of light has been seducing travellers for centuries. Walk cobblestone streets, savour world-class cuisine and discover timeless art and architecture in the most romantic city on earth.",
    highlights: ["Private Eiffel Tower summit experience","Seine river dinner cruise","Versailles Palace & gardens full-day tour","Louvre Museum with skip-the-line access","Montmartre art district walking tour","Champagne tasting in a historic cellar"],
    inclusions: ["Return economy flights","5 nights boutique hotel near Champs-Élysées","Daily breakfast","Paris Museum Pass (4 days)","Seine dinner cruise","Airport transfers"],
    exclusions: ["Schengen visa fees","Travel insurance","Lunches and dinners (except cruise)","Personal shopping"],
    itinerary: [
      { day: 1, title: "Bonjour, Paris!", description: "Arrive in the City of Light.", activities: ["CDG Airport transfer","Hotel check-in","Stroll along the Seine","Welcome dinner in Le Marais"] },
      { day: 2, title: "Iconic Landmarks", description: "Visit the most iconic monuments.", activities: ["Eiffel Tower visit","Champ de Mars picnic","Arc de Triomphe","Champs-Élysées evening walk"] },
      { day: 3, title: "Art & History", description: "Immerse yourself in the world's greatest art.", activities: ["Louvre Museum (skip-the-line)","Tuileries Garden","Musée d'Orsay","Latin Quarter dinner"] },
      { day: 4, title: "Versailles Escape", description: "A full day exploring the Sun King's palace.", activities: ["Palace of Versailles","Hall of Mirrors","French formal gardens","Marie Antoinette's estate"] },
      { day: 5, title: "Montmartre & Moulin Rouge", description: "Bohemian art district and the glamorous Moulin Rouge.", activities: ["Sacré-Cœur basilica","Artist village & studios","Seine dinner cruise","Optional Moulin Rouge show"] },
      { day: 6, title: "Au Revoir", description: "Last morning to pick up souvenirs.", activities: ["Final café breakfast","Shopping in Galeries Lafayette","CDG transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1541778480-fc7aecf85f19?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 16, category: "Romantic", isFeatured: false, isTrending: false, isPublished: true,
  },
  {
    slug: "dubai-desert-glamour",
    title: "Dubai Desert & Glamour",
    destination: "Dubai",
    country: "UAE",
    theme: "Cultural",
    durationNights: 4,
    durationDays: 5,
    price: "99999",
    offerPrice: "79999",
    currency: "INR",
    rating: 4.6,
    reviewCount: 412,
    overview: "Where ancient desert meets futuristic skyline — Dubai is a sensory marvel. From gold-souks and camel rides to Burj Khalifa's observation deck and lavish brunches, this city never stops dazzling.",
    highlights: ["Burj Khalifa 124th floor At The Top","Desert safari with dune bashing & camel ride","Dhow cruise dinner on Dubai Creek","Dubai Mall & indoor ski slope","Gold & Spice Souk tour","Luxury hotel brunch experience"],
    inclusions: ["Return flights from India","4 nights 5-star hotel","Daily breakfast","Desert safari with dinner","Dhow cruise dinner","Airport transfers"],
    exclusions: ["Travel insurance","Visa fees","Alcoholic beverages","Optional tours and shopping"],
    itinerary: [
      { day: 1, title: "Welcome to Dubai", description: "Land in the UAE's glittering gem.", activities: ["DXB Airport transfer","Hotel check-in","Dubai Marina walk","Dinner at JBR Beach"] },
      { day: 2, title: "Iconic Dubai", description: "The ultimate Dubai day.", activities: ["Burj Khalifa At The Top","Dubai Mall shopping","Dubai Fountain show","Dinner at a rooftop restaurant"] },
      { day: 3, title: "Desert Safari", description: "Venture into the vast Arabian desert.", activities: ["Dune bashing in 4x4","Camel ride","Sandboarding","Bedouin camp BBQ dinner"] },
      { day: 4, title: "Old Dubai & Creek", description: "Discover the soul of historic Dubai.", activities: ["Gold Souk","Spice Souk","Abra water taxi ride","Dhow cruise dinner on Dubai Creek"] },
      { day: 5, title: "Free Morning & Departure", description: "Last morning before flying home.", activities: ["Hotel brunch","Free leisure time","Airport transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1548813814-5fe8e0826e16?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1496568816309-51d7c20e3b21?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 20, category: "Cultural", isFeatured: false, isTrending: true, isPublished: true,
  },
  {
    slug: "thailand-island-adventure",
    title: "Thailand Island Adventure",
    destination: "Phuket & Krabi",
    country: "Thailand",
    theme: "Adventure",
    durationNights: 7,
    durationDays: 8,
    price: "94999",
    offerPrice: "74999",
    currency: "INR",
    rating: 4.7,
    reviewCount: 389,
    overview: "Emerald seas, dramatic limestone karsts and the legendary Thai smile — Thailand's southern islands are a playground for adventurers and beach lovers alike.",
    highlights: ["Phi Phi Islands speedboat day trip","Kayaking through Phang Nga Bay sea caves","James Bond Island excursion","Thai cooking class with local family","Night market food trail in Krabi","Sunrise yoga on the beach"],
    inclusions: ["Return flights from India","7 nights beach resort accommodation","Daily breakfast & 2 dinners","Phi Phi Islands tour","Phang Nga Bay tour","All airport & inter-island transfers"],
    exclusions: ["Visa on arrival fee (~₹2,500)","Travel insurance","Optional scuba diving","Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrival in Phuket", description: "Land in tropical Thailand.", activities: ["Airport transfer","Check-in","Welcome dinner at beach restaurant"] },
      { day: 2, title: "Phi Phi Islands", description: "Speedboat adventure to the iconic Phi Phi archipelago.", activities: ["Speedboat to Phi Phi Don","Monkey Beach","Maya Bay snorkeling","Viking Cave"] },
      { day: 3, title: "Old Town & Markets", description: "Explore Phuket's Sino-Portuguese old town.", activities: ["Phuket Old Town walk","Big Buddha","Sunday Walking Street night market"] },
      { day: 4, title: "Transfer to Krabi", description: "Ferry across to dramatic Krabi.", activities: ["Ferry to Krabi","Railay Beach","Rock climbing intro session"] },
      { day: 5, title: "Phang Nga Bay", description: "Kayak through sea caves.", activities: ["Sea kayaking","James Bond Island","Floating village visit","Mangrove tour"] },
      { day: 6, title: "Four Islands", description: "Snorkel four pristine islands.", activities: ["Longtail boat tour","Chicken Island","Tub Island","Bamboo Island snorkeling"] },
      { day: 7, title: "Thai Cooking & Culture", description: "Learn authentic Thai cooking.", activities: ["Morning market visit","Thai cooking class","Temple visit","Night market food trail"] },
      { day: 8, title: "Departure", description: "Last morning at the beach.", activities: ["Sunrise yoga","Farewell breakfast","Airport transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 14, category: "Adventure", isFeatured: false, isTrending: false, isPublished: true,
  },
  {
    slug: "kerala-backwater-bliss",
    title: "Kerala Backwater Bliss",
    destination: "Kerala",
    country: "India",
    theme: "Cultural",
    durationNights: 5,
    durationDays: 6,
    price: "54999",
    offerPrice: "39999",
    currency: "INR",
    rating: 4.8,
    reviewCount: 521,
    overview: "God's Own Country unfolds in layers of verdant beauty — houseboat journeys through shimmering backwaters, spice plantation walks, Ayurvedic healing and the classical rhythms of Kathakali.",
    highlights: ["Overnight luxury houseboat in Alleppey","Periyar Wildlife Sanctuary safari","Munnar tea plantation walk","Ayurvedic spa & wellness retreat","Kathakali dance performance","Spice plantation tour in Thekkady"],
    inclusions: ["5 nights accommodation (hotel + houseboat)","Daily breakfast & dinner","All sightseeing transfers","Houseboat overnight with all meals","Ayurveda massage session","English-speaking guide"],
    exclusions: ["Flights to/from Kochi","Travel insurance","Personal expenses","Camera fees at sanctuaries"],
    itinerary: [
      { day: 1, title: "Arrival in Kochi", description: "Arrive in Fort Kochi.", activities: ["Kochi Airport pickup","Chinese fishing nets","Fort Kochi walk","Kathakali performance"] },
      { day: 2, title: "Munnar Highlands", description: "Drive into the cool hill station of Munnar.", activities: ["Drive to Munnar","Tea Museum visit","Tea plantation walk","Echo Point"] },
      { day: 3, title: "Thekkady Spice Trail", description: "Explore the world of spices.", activities: ["Periyar Wildlife Sanctuary boat safari","Spice plantation tour","Elephant encounter","Traditional dinner"] },
      { day: 4, title: "Alleppey Houseboat", description: "Board your private luxury houseboat.", activities: ["Transfer to Alleppey","Houseboat embarkation","Backwater cruise","Sunset on the water","Dinner on board"] },
      { day: 5, title: "Backwaters & Kovalam", description: "Morning on the water then head to Kovalam beach.", activities: ["Sunrise on houseboat","Disembark & transfer to Kovalam","Beach afternoon","Ayurvedic massage"] },
      { day: 6, title: "Departure", description: "Last morning of tranquility.", activities: ["Beachside breakfast","Trivandrum Airport transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1593696140826-c58b021acf8b?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1545041662-a5b342ef95c2?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 10, category: "Cultural", isFeatured: true, isTrending: false, isPublished: true,
  },
  {
    slug: "singapore-city-family",
    title: "Singapore City & Sentosa",
    destination: "Singapore",
    country: "Singapore",
    theme: "Family",
    durationNights: 4,
    durationDays: 5,
    price: "119999",
    offerPrice: "94999",
    currency: "INR",
    rating: 4.6,
    reviewCount: 267,
    overview: "A futuristic garden city where cultures collide and the extraordinary is ordinary. Universal Studios thrills, Gardens by the Bay dazzles, and incredible hawker food awaits at every turn.",
    highlights: ["Universal Studios Singapore full day","Gardens by the Bay & Supertree Grove","Sentosa Island beach & cable car","Singapore Night Safari","Marina Bay Sands infinity pool view","Chinatown, Little India & Arab Street food trail"],
    inclusions: ["Return economy flights","4 nights hotel in Sentosa or Marina Bay","Daily breakfast","Universal Studios entry tickets","Gardens by the Bay tickets","Night Safari tickets","Airport transfers"],
    exclusions: ["Visa (free for Indian passport holders up to 30 days)","Travel insurance","Lunches and dinners","Personal shopping"],
    itinerary: [
      { day: 1, title: "Arrival & Sentosa", description: "Touchdown in the Lion City.", activities: ["Changi Airport arrival","Hotel check-in","Sentosa beach","Cable car ride","Siloso Beach evening"] },
      { day: 2, title: "Universal Studios", description: "A full day of world-class theme park thrills.", activities: ["Universal Studios opening","All zone rides","Character meet & greet","Dinner at Resorts World"] },
      { day: 3, title: "Gardens & Bay", description: "Marvel at one of the world's most breathtaking urban gardens.", activities: ["Gardens by the Bay","Cloud Forest dome","Flower Dome","Marina Bay Sands rooftop","Light & Sound show"] },
      { day: 4, title: "Cultural Quarters & Safari", description: "Explore Singapore's multicultural neighbourhoods.", activities: ["Chinatown dim sum breakfast","Little India walk","Arab Street","Singapore Zoo","Night Safari"] },
      { day: 5, title: "Free Morning & Departure", description: "Orchard Road shopping and farewell.", activities: ["Orchard Road shopping","Hawker centre lunch","Changi Airport transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1565967511849-76a60a516170?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 20, category: "Family", isFeatured: false, isTrending: false, isPublished: true,
  },
  {
    slug: "goa-sun-surf-soul",
    title: "Goa: Sun, Surf & Soul",
    destination: "Goa",
    country: "India",
    theme: "Beach",
    durationNights: 3,
    durationDays: 4,
    price: "34999",
    offerPrice: "24999",
    currency: "INR",
    rating: 4.5,
    reviewCount: 634,
    overview: "India's beloved beach paradise — where Portuguese architecture meets golden sands and a carefree spirit fills the salty air. Whether you crave surf, spice, parties or peace, Goa delivers it all.",
    highlights: ["North Goa beaches — Baga, Calangute & Anjuna","Sunset cruise on the Mandovi River","Old Goa UNESCO heritage churches","Spice plantation tour with lunch","Water sports at Calangute Beach","Flea market at Anjuna"],
    inclusions: ["Return flights from major cities","3 nights beachside resort","Daily breakfast","Sunset river cruise","Spice plantation visit with lunch","Airport transfers"],
    exclusions: ["Water sports activities","Lunches and dinners (except plantation)","Travel insurance","Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrival & North Goa", description: "Fly in and head straight to the beach.", activities: ["GOI Airport pickup","Check-in at resort","Baga Beach afternoon","Tito's Lane evening"] },
      { day: 2, title: "Heritage & Culture", description: "Explore Goa's storied Portuguese past.", activities: ["Old Goa basilicas","Spice plantation tour & lunch","Panjim market","Mandovi sunset cruise"] },
      { day: 3, title: "Beaches & Water Sports", description: "Full day of sun, sea and adrenaline.", activities: ["Calangute water sports","Parasailing & jet ski","Anjuna flea market","Beach shack dinner"] },
      { day: 4, title: "Departure", description: "Last morning sunrise at the beach.", activities: ["Sunrise walk","Checkout breakfast","Airport transfer"] },
    ],
    images: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1580019542155-247062e19ce4?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?q=80&w=1400&auto=format&fit=crop"],
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1400&auto=format&fit=crop",
    maxTravelers: 20, category: "Beach", isFeatured: false, isTrending: true, isPublished: true,
  },
];

async function seed() {
  console.log("Seeding packages…");
  for (const pkg of packages) {
    await db.insert(packagesTable).values(pkg as any).onConflictDoNothing();
    console.log(`  ✓ ${pkg.title}`);
  }
  console.log("Done.");
  await pool.end();
}

seed().catch(e => { console.error(e); process.exit(1); });
